---
home: /home/lujeni

user: lujeni

group: lujeni

system_apt_key:
  - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  - "https://baltocdn.com/helm/signing.asc"
  - "https://download.docker.com/linux/ubuntu/gpg"

system_apt_repository:
  - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
  - "deb https://baltocdn.com/helm/stable/debian/ all main"
  - "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

system_package:
  - ansible
  - apt-transport-https
  - build-essential
  - ca-certificates
  - cryptsetup # yubi
  - curl
  - dirmngr # yubi
  - feh
  - gcc
  - git
  - gnupg
  - gnupg-agent # yubi
  - gnupg2 # yubi
  - golang
  - helm
  - hopenpgp-tools # yubi
  - htop
  - iotop
  - jq
  - keychain
  - kubectl
  - libbz2-dev # pyenv
  - libffi-dev # pyenv
  - libncurses-dev # pyenv
  - libreadline-dev # pyenv
  - libsqlite3-dev # pyenv
  - lsb-release
  - lzma-dev # pyenv
  - make
  - openvpn
  - pcscd # yubi
  - pip
  - pnmixer
  - python-is-python3
  - scdaemon # yubi
  - scrot
  - secure-delete # yubi
  - ssh
  - tig
  - tree
  - unp
  - virtualenv
  - xclip
  - yubikey-personalization  # yubi

system_snap_package:
  - mattermost-desktop

docker_repo_prefix: lujeni

docker_images:
  - aws
  - chrome

docker_images_version: 1.0.0

system_sources_files:
  - bash-git-prompt/gitprompt.sh
  - bash_aliases
  - completion_kubectx
  - completion_kubens
  - dockerfunc
  - exports
  - func
  - kubectl_aliases
