- name: docker | x11docker directory
  ansible.builtin.file:
    path: /opt/x11docker
    state: directory
    mode: 0755

- name: docker | x11docker get
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker
    dest: /opt/x11docker/installer
    mode: 0755

- name: docker | x11docker install
  ansible.builtin.shell: /opt/x11docker/installer --update
  args:
    executable: /bin/bash

- name: docker | install
  apt:
    package: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: docker | adding existing user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: docker | enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker
    - containerd

- name: docker | data
  file:
    path: "{{ home }}/docker/{{ item[0] }}/{{ item[1] }}"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0755
    state: directory
  with_nested:
    - ["data", "dockerfiles"]
    - "{{ docker_images }}"

- name: docker | deploy
  template:
    src: "docker/{{ item }}/Dockerfile.j2"
    dest: "{{ home }}/docker/dockerfiles/{{ item }}/Dockerfile"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644
  loop: "{{ docker_images }}"

- name: docker | deploy | mattermost extra directory
  file:
    path: "{{ home }}/docker/data/mattermost-desktop/{{ item }}"
    group: "{{ group }}" # NOTE: chrome user in Docker image
    owner: "{{ user }}" # NOTE: chrome user in Docker image
    mode: 0755
    state: directory
  loop:
    - config
    - downloads

- name: docker | deploy | chrome extra directory
  file:
    path: "{{ home }}/docker/data/chrome/{{ item }}"
    group: "999" # NOTE: chrome user in Docker image
    owner: "999" # NOTE: chrome user in Docker image
    mode: 0755
    state: directory
  loop:
    - data
    - downloads
 
- name: docker | deploy | chrome local font
  template:
    src: "docker/chrome/local.conf"
    dest: "{{ home }}/docker/dockerfiles/chrome/local.conf"
    group: "{{ group }}"
    owner: "{{ user }}"
    mode: 0644

- name: docker | deploy | chrome volume rights
  file:
    path: "{{ home }}/docker/data/chrome/"
    group: "999"
    owner: "{{ user }}"
    mode: 0775

      # - name: docker | build
      #   shell: |
      #     cd {{ home }}/docker/dockerfiles/{{ item }} && \
      #     docker build . -t {{ docker_repo_prefix }}/{{ item }}:{{ docker_images_version }}
      #   loop: "{{ docker_images }}"
