---
- name: i3 | Check if i3 is installed
  package_facts:
    manager: apt
  tags: [i3, install]

- name: i3 | Install required packages
  apt:
    name: "{{ i3_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    i3_packages:
      - i3
      - py3status
  register: i3_install
  notify: restart i3
  tags: [i3, install]

- name: i3 | Ensure configuration directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(user) }}"
    group: "{{ item.group | default(group) }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
  loop:
    - path: "{{ home }}/.config/i3"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: "0775"
    - path: "/etc/py3status.d"
      owner: "root"
      group: "{{ group }}"
      mode: "0775"
  tags: [i3, config]

- name: i3 | Deploy configuration files
  ansible.builtin.template:
    src: "i3/{{ item }}.j2"
    dest: "{{ home }}/.config/i3/{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"
    backup: yes
    validate: "i3 -C -c %s"
  loop:
    - config
    - i3status.conf
  register: i3_config
  notify: reload i3
  tags: [i3, config]
