- name: neovim | ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: neovim | install
  apt:
    package: "{{ item }}"
  loop:
    - neovim

- name: neovim | copy
  ansible.builtin.copy:
    src: files/nvim
    dest: "{{ home }}/.config/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: neovim | symlink
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    owner: root
    group: root
    state: link
