---
- name: restart i3
  command: "i3-msg restart"
  become: yes
  become_user: "{{ user }}"
  listen: restart i3

- name: reload i3
  command: "i3-msg reload"
  become: yes
  become_user: "{{ user }}"
  listen: reload i3
